

include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - lib/widget/*
linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: false
    lines_longer_than_80_chars: false